services:
  client:
    container_name: onestop-client
    environment:
      - PORT=4000
    build:
      context: .
      target: production
    restart: unless-stopped
    command: pnpm ssr:client --host=0.0.0
    ports:
      - '4000:4000'

  admin:
    container_name: onestop-admin
    environment:
      - PORT=4100
    build:
      context: .
      target: production
    restart: unless-stopped
    command: pnpm ssr:admin --host=0.0.0
    ports:
      - '4100:4100'
